PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.org/trends#>
PREFIX ex: <http://example.org/trends#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>

################### QUERY 1 ###################

SELECT ?query ?category
WHERE {
  ?record a ex:TrendRecord ;
          ex:query ?query ;
          ex:category ?category .
}

################### QUERY 2 ###################

SELECT ?record ?category ?location ?query ?rank ?trendyear ?wikidataLabel ?description
WHERE {
    # Datos locales
    ?record a ex:TrendRecord ;
            ex:category ?category ;
            ex:location ?location ;
            ex:query ?query ;
            ex:rank ?rank ;
            ex:year ?trendyear ;
            ex:wikidata ?wikidata .
    
#    # Filtrar por la entidad específica
#    FILTER(?record = <http://example.org/trends/record/0007d8e6-49b0-4434-92c7-bdc2e077dd18>)
#    
    # Consulta federada a Wikidata
    SERVICE <https://query.wikidata.org/sparql> {
        ?wikidata rdfs:label ?wikidataLabel ;
                  schema:description ?description .
        FILTER(LANG(?wikidataLabel) = "en")
        FILTER(LANG(?description) = "en")
    }
} LIMIT 10


################### QUERY 3 ###################

SELECT ?record ?category ?location ?query ?rank ?trendyear ?wikidataLabel ?description ?wikidataCategoryLabel
WHERE {
    # Datos locales
    ?record a ex:TrendRecord ;
            ex:category ?category ;
            ex:location ?location ;
            ex:query ?query ;
            ex:rank ?rank ;
            ex:year ?trendyear ;
            ex:wikidata ?wikidata .

    # Consulta federada a Wikidata
    SERVICE <https://query.wikidata.org/sparql> {
        ?wikidata rdfs:label ?wikidataLabel ;
                  schema:description ?description ;
                  wdt:P31 ?wikidataCategory .
        ?wikidataCategory rdfs:label ?wikidataCategoryLabel .
        FILTER(LANG(?wikidataLabel) = "es")
        FILTER(LANG(?description) = "es")
        FILTER(LANG(?wikidataCategoryLabel) = "es")
    }
}
LIMIT 10

################### Query 4 ################### Grafico de genero
SELECT ?trendyear ?genderLabel (COUNT(?record) AS ?count)
WHERE {
    # Datos locales
    ?record a ex:GlobalTrend ;
            ex:year ?trendyear ;
            ex:wikidata ?wikidata .

    # Consulta federada a Wikidata
    SERVICE <https://query.wikidata.org/sparql> {
        ?wikidata wdt:P21 ?gender ;  # P21 es la propiedad de género en Wikidata
    }

    # Obtener etiquetas de género
    SERVICE <https://query.wikidata.org/sparql> {
        ?gender rdfs:label ?genderLabel .
        FILTER(LANG(?genderLabel) = "en")
    }
}
GROUP BY ?trendyear ?genderLabel
ORDER BY ?trendyear ?genderLabel

################### Query 5 ################### Grafico de tendencias en USA

# Trends relacionados con Estados Unidos por año
SELECT ?trendyear ?usEntity (COUNT(?record) AS ?count)
WHERE {
    # Datos locales
    ?record a ex:TrendRecord ;
            ex:year ?trendyear ;
            ex:wikidata ?wikidata .

    # Consulta federada a Wikidata
    SERVICE <https://query.wikidata.org/sparql> {
        ?wikidata (wdt:P17 | wdt:P27) wd:Q30 .  # P17: country, P27: country of citizenship; Q30: United States
        BIND("United States" AS ?usEntity)
    }
}
GROUP BY ?trendyear ?usEntity
ORDER BY ?trendyear

# Trends por año
SELECT ?trendyear (COUNT(?record) AS ?count)
WHERE {
    ?record a ex:TrendRecord ;
            ex:year ?trendyear .
}
GROUP BY ?trendyear
